### ISSUE TITLE
GeoCoding / ReverseGeoCoding API 제공 업체 선정 

### ISSUE THREAD

**Issue by mingmingmon** [Mu-necting/Mu-necting_Server_V4#12]
## 개요

2024년 8월 5일(월) 뮤넥팅 정기회의에서 결정된 사안인 
**IOS가 위도, 경도 정보를 서버 제공하고 서버는 해당 위치의 주소 정보를 전달하는 엔드포인트를 작성**하기 위해 다양한 GeoCoding API 제공 업체를 비교해보았습니다.

## 개념 설명

`GeoCoding`이란 고유명칭(주소나 산,호수의 이름등)을 가지고 위도와 경도의 좌표값를 얻는 것을 말합니다.
`ReverseGeoCoding`이란 GeoCoding과 반대로 위도와 경도의 좌표값을 가지고 주소명을 얻는 것을 말합니다.

현재 **필요한 기술은 ReverseGeoCodig**입니다.

### 1. 네이버 클라우드 

> **네이버 이메일 한 계정에 대해서 3,000,000건 / 월 (3백만건)에 대해 무료 -> 100,000건 / 일 인셈
> 그 이후는 0.5 원 / 건으로 요금 발생**

API 가이드 : (https://api.ncloud-docs.com/docs/ai-naver-mapsreversegeocoding)
Maps > ReverseGeoCoding 대표 계정에 대한 설명 : (https://www.ncloud.com/support/faq/prod/2828)
Maps > ReverseGeoCoding 요금 정책 : (https://www.ncloud.com/charge/region/ko)

### 2. TMAP

> **FREE 요금제는 20,000건 / 일**

API 가이드 : (https://tmapapi.tmapmobility.com/main.html#webservice/docs/reverseGeocoding)
GeoCoding 요금 : (https://openapi.sk.com/products/calc?svcSeq=4&menuSeq=5)

### 3. 카카오 MAP

> **300,000건 / 일 무료 사용**

API 가이드1 : (https://apis.map.kakao.com/web/documentation/#services_Geocoder)
API 가이드2 :(https://developers.kakao.com/docs/latest/ko/local/dev-guide#coord-to-address-request)

### 4. 구글 
> ![image](https://github.com/user-attachments/assets/7a09b752-9649-4a8a-8e7f-6c9fdd488810)

API 가이드1 : (https://github.com/hyalen-caldeira/inauth)
API 가이드2 : (https://developers.google.com/maps/documentation/javascript/libraries?hl=ko&_gl=1*uqdnxe*_up*MQ..*_ga*MTU5MjAyNDQzNy4xNzIzMDgyMTAy*_ga_NRWSTWS78N*MTcyMzA4MjEwMS4xLjAuMTcyMzA4MjE4MS4wLjAuMA..)
SKU > GeoCoding 요금 : (https://developers.google.com/maps/billing-and-pricing/pricing?hl=ko#geocoding)

### 5. 자체 개발 
블로그 자료 : (https://blog.naver.com/airguy76/221521346348)

## 결론

1. **자체 개발**은 작업 난이도가 높고 시간이 오래 걸리기 때문에 **8월 앱출시 내에서는 불가능**할 것 같습니다. 이후 뮤넥팅 서비스가 발전되어 자체 MAP을 개발해야 되는 규모가 된다면 시도해보고 싶습니다.
2. **구글**의 경우 대한민국 뿐만 아니라 해외 지도 정보까지 가지고 있는 장점이 있습니다. 그러나 뮤넥팅은 현재 **타케팅을 대한민국** 내로 할 예정이고 구글은 비용이 **가장 비싸기 때문에 후순위**로 밀렸습니다.
3. **네이버 클라우드**는 3,000,000건 / 월를 **초과하면 비용을 지불하고 계속 쓸 수 있는 장점**이 있습니다.
4. 그러나 출시 초기에는 **카카오 MAP에서 무료로 제공하는 300,000건 / 일 스펙으로 충분히 위치 정보 요청을 처리**할 수 있을 것 같습니다. 아마 카카오 MAP에서 제공하는 **하루 무료 건수를 다 사용하면 좌표 요청 API를 사용할 수 없을 것**입니다.
5. **뮤넥팅 서비스가 성장**하여 카카오 MAP에서 제공하는 300,000건 / 일을 초과할 경우 **TMAP, 네이버 클라우드 등등과 혼합**해서 사용하는 방향으로 갈 예정입니다.

결론적으로 **카카오 MAP API**가 뮤넥팅 서비스에 가장 적합하다고 생각하였습니다. 
해당 내용을 공유하고 다른 분들의 의견을 듣고자 합니다. **편하게 코멘트 달아주세요**!

**Comment by soycong** [comment]
제안해주신 것처럼 초기 개발은 카카오맵이 가장 좋아보입니다!

**Comment by seunghyeonKang** [comment]
저도 제안주신대로 카카오맵 사용 후, 차후에 네이버 클라우드 등 혼용 사용 동의합니다. 깔끔한 정리 감사합니다!

**Comment by mungsil** [comment]
정리 감사합니다! 정리해주신 내용과 더불어, **카카오 API** 와 관련해서 알아본 결과 알게된 몇 가지 추가적인 사실을 공유하고자 합니다.

1. 검색 결과 300,000건 / 일을 초과하는 경우 유료 계약을 통해서 요금을 지불하고 사용하는 방향도 있음을 확인하였습니다. (https://devtalk.kakao.com/t/api/137760) 

2.  카카오 API의 통합 무료 제공량은 월 300만 건으로 네이버 AP를 사용하는 경우와 동일할 것 같습니다.
![image](https://github.com/user-attachments/assets/0ee80e2a-7f40-440e-831f-685fd2572da9)

3. 좌표를 주소로 변환하는 API의 경우, 카카오 지도 API가 아닌 로컬 API를 사용해야 하는 것으로 확인하였습니다.

![image](https://github.com/user-attachments/assets/54029dd3-e77d-4941-a99d-ed91f0b4ed7f)

로컬 API의 경우 무료 제공량이 100,000건 / 일으로 알고 있으나 이는 네이버 API와 비슷한 수준으로 초기 서비스에서는 문제가 되지 않은 것으로 예상됩니다.

### 결론
 요금 측면에서는 네이버 또는 카카오 API 중 어떤 것을 사용해도 괜찮을 것 같다는 생각이 들었습니다.  지도맵과의 연동, API 문서화 등의 추가적인 요소를 고려하여 결정하면 좋을 것 같습니다.

**Comment by seonwoonam** [comment]
제안해주신 것처럼 카카오맵또는 네이버 api를 사용하는 것이 좋은거 같습니다!

**Comment by sjghub** [comment]
정리 너무 깔끔해서 보면서 이해하기 편합니다!!
결론 5번에 동의합니다
