### ISSUE TITLE
좋아요 기능 기획 정리

### ISSUE THREAD

**Issue by mungsil** [Mu-necting/Mu-necting_Server_V4#21]
## 목적
`좋아요` 기능 개발에 앞서 `좋아요`기능과 관련하여 논의되었던 사항을 크로스 체크하고자 합니다.

## 확인사항
지난 월요일 회의 내용을 토대로 정리해보았을 때, 해당 기능은 다음과 같은 요구사항을 가진다고 생각하였습니다.
- 노래에 `좋아요`를 누를 수 있다.
- `좋아요`를 누르면 좋아요 개수가 표시된다.
- `좋아요`를 누른 음악 리스트는 마이페이지에서 접근 가능하다.
- `좋아요 음악 리스트`에서 노출되는 음악은 30초 미리듣기만 가능하며, 특정 음악 클릭 시 해당 음악의 상세 페이지로 이동 가능하다.

혹시 제가 잘못 인지하고 있거나 놓치고 있는 부분이 있다면 편하게 말씀해 주시면 감사하겠습니다 :)

**Comment by mingmingmon** [comment]
제가 이해한 것과 일치합니다! 
특정 음악 클릭 시 음악의 상세 페이지 화면은 아래와 같은 걸까요? 
Design figma > Screens > Listening에서 따왔습니다.
<img width="165" alt="image" src="https://github.com/user-attachments/assets/56d848c9-705f-4786-bd26-7639ec40528e">

**Comment by mungsil** [comment]
네 맞습니다! 저도 해당 화면을 생각했었어요

**Comment by soycong** [comment]
네!! 저도 동일하게 생각합니다!
정리 감사합니다 :-) 👍
