### ISSUE TITLE
좋아요 누르기/취소하기 switch API 작성 제안

### ISSUE THREAD

**Issue by mingmingmon** [Mu-necting/Mu-necting_Server_V4#34]
리팩토링 작업 중 @mungsil님의 좋아요 API 구현을 보면서 한 가지 제안 드리고 싶은 부분을 발견했어요.

현재는 아래 코드처럼 좋아요 누르기와 취소하기 API가 구분되어 있습니다. 

```
@RestController
@RequiredArgsConstructor
@RequestMapping("/tracks")
@Tag(name = "like", description = "Like 관련 api </br> <i> 담당자 : 김송은 </i>")
public class LikeController {

    private final LikeService likeService;

    @PostMapping("/{trackId}/likes")
    @Operation(summary = "좋아요 누르기")
    public ApiResponse<?> addTrackLike(
            @PathVariable(name = "trackId") String trackId,
            @UserId Long userId
    ) {
        AddTrackLikeResponseDto dto = likeService.addTrackLike(trackId, userId);
        return ApiResponse.onSuccess(Status.CREATED.getCode(), Status.CREATED.getMessage(), dto);
    }

    @GetMapping("/liked")
    @Operation(summary = "좋아요한 음악 조회")
    public ApiResponse<?> getLikedTracks (
            @UserId Long userId,
            @RequestParam(required = false) Long cursor,
            @RequestParam(required = false, defaultValue = "20") int size
    ) {
        GetLikedTrackListResponseDto dto = likeService.getLikedTracks(userId, cursor, size);
        return ApiResponse.onSuccess(Status.OK.getCode(), Status.OK.getMessage(), dto);
    }

    @DeleteMapping("/{trackId}/likes")
    @Operation(summary = "좋아요 취소")
    public ApiResponse<?> deleteTrackLike (
            @PathVariable(name = "trackId") String trackId,
            @UserId Long userId
    ) {
        DeleteTrackLikeResponseDto dto = likeService.deleteTrackLike(trackId, userId);
        return ApiResponse.onSuccess(Status.OK.getCode(), Status.OK.getMessage(), dto);
    }
}
```

이런 경우 사용자가 "좋아요"를 눌렀으면 취소하기 API를 호출해야 하고, 
"좋아요"를 누르지 않았으면 좋아요 누르기 API를 호출해야 합니다. 

따라서 추가적으로 trackId와 memberId로 "좋아요"를 눌렀는지 확인해야 하는 API가 필요해 보입니다.
이럴 경우 백엔드에서 작성해야 하는 API도 많아지고, 클라이언트 측에서도 API 요청을 2번 보내야 합니다.

이에 trackId와 memberId를 통해 좋아요가 눌린 상태면 취소를, 눌리지 않은 상태면 좋아요를 표시할 수 있도록 
상태를 전환하는 `switchLikeStatus `API 작성을 제안드려요.

**Comment by mungsil** [comment]
꼼꼼하게 확인해주셔서 감사합니다 :)

다만 현재 유저가 "좋아요"를 누른 상태인지는 `/api/tracks/{trackId}/details` API의 응답 DTO에서 `isLiked` 필드를 통해 확인할 수 있습니다.  `/api/tracks/{trackId}/details` API는 댓글과 좋아요의 개수, 좋아요 상태를 반환하는 API입니다. 따라서 유저가 음악을 조회할 때마다 항상 호출이 이루어질 것이라고 예상됩니다. 그래서 걱정해주신 부분은 문제가 생기지 않을 것으로 생각해요.

제안해주신 내용을 보고 추가적으로 생각난 개선 방안이 있습니다.
현재 좋아요 생성, 취소 API의 로직이 유사하다는 점과  응답 DTO의 필드가 동일하다는 점을 고려해서,  `/api/tracks/{trackId}/likes?status={boolean}` API를 설계하여 좋아요 생성과 취소를 하나의 API로 구현 가능할 것 같습니다.

추후 확장성이나 변동성을 고려하자면 기존의 로직을 유지하고, 코드의 간결함을 생각하면 `/api/tracks/{trackId}/likes?status={boolean}`을 새로 생성하는 방안이 좋을 것 같아요. 

저의 답변에 대해서 어떻게 생각하시는 지 의견을 여쭤봐도 될까요?

**Comment by mingmingmon** [comment]
답변 감사해요.

1. "좋아요"를 누른 상태인지 굳이 추가적인 API 요청을 하는 것이 아닌, 이미 화면을 구성할 때 해당 `track`에 대한 "좋아요"와 댓글 개수를 알아야 하기 때문에 그때 `isLiked `필드로 확인이 가능하다는 것 확인했습니다!
2. 그럼 굳이 `switchLikeStatus` API를 새로 만들지 않고 status를 입력 받아 누르기/취소하기를 구현하는 것에 동의합니다! **아마도 `status`의 입력으로는 `!isLiked`가 들어오는 것일까요?** 즉 프론트측에서 현재 "좋아요"의 상태 `isLiked`의 역을 전달해서 해당 상태로 `like `테이블을 수정하는 것이죠

**Comment by mungsil** [comment]
말씀해주신 것과 동일한 생각입니다!
 현재 좋아요가 눌려져 있는 상태라면, `status=false`를 통해 좋아요를 취소합니다. 좋아요가 눌러져 있지 않다면, `status=true`를 통해 좋아요를 생성합니다.

그런데 `status` 라는 이름이 다소 직관적이지 못하다는 생각이 들었습니다. 그래서, 더 좋은 이름을 고민하다가 "쿼리 파라미터는 리소스 필터링 또는 정렬에 사용하는 것이 restful한 설계에 적합하다"는 내용을 알게 되었어요. 
([stackoverflow ](https://stackoverflow.com/questions/30967822/when-do-i-use-path-parameters-vs-query-parameters-in-a-restful-api/31261026#31261026)질문글을 공유 드립니다! )
제가 제안 드린 방식을 사용하게 된다면 쿼리 파라미터로 필터링/정렬이 아닌 리소스의 상태를 업데이트 하는 것이 되므로, 부적합한 설계라는 생각이 들었습니다.

따라서 조금 더 restful한 설계를 하고자 한다면 기존의 `API`를 유지하는게 더 적합할 것 같아요. 저는 이 방법이 더 나은 선택이라고 생각하는데, 이에 대해 어떻게 생각하시나요?

**Comment by mingmingmon** [comment]
쿼리 파라미터를 리소스의 상태를 업데이트 하는 것으로 사용하는 것이 부적절하군요!

결국 trackId에 대해서 "좋아요" 개수와 댓글 개수를 확인해야 하니, `/api/tracks/{trackId}/details`을 호출할 것이고
그 때 좋아요 여부를 확인할 수 있는 isLiked 필드가 있으니 굳이 좋아요 여부 확인용 API를 작성할 필요가 없는건 여전하군요.

그리고 isLiked 값에 따라서 기존의 2개의 API 중 좋아요 누르기 VS 좋아요 취소하기를 프론트 측에서 호출하도록 하는 방법에 동의합니다!
