### ISSUE TITLE
추가 리팩토링 사항 제안

### ISSUE THREAD

**Issue by mungsil** [Mu-necting/Mu-necting_Server_V4#36]
1. 현재 `MusicController`의 음악 업로드 API, `CommentController`에 위치한 일부 API의 응답으로 `id` 값만을 반환하고 있습니다.  저는 이를 `DTO`에 담아 반환하는 것을 제안드립니다.

      예시로 `@UserId` 테스트용 API(삭제 예정)의 응답 값을 보여드릴게요.
      ```
      {
        "isSuccess": true,
        "code": "COMMON200",
        "message": "성공입니다.",
        "data": 1
      }
      ```
      이러한 방식의 응답은 1이라는 응답 값이 **어떠한 정보**에 대한 값인지 명시해주지 않는 응답입니다. (해당 `API`는 기능이 잘 동작하는지 확인하는 테스트 용도로서의 `API`이므로 `DTO`에 값을 담아주지 않았어요) 
      
      ` id `정보에 대한 값이라는 것을 나타내기 위해 `id` 필드를 가지는 `DTO`를 생성하여 값을 담아 반환하면 명확하게 값을 식별할 수 있을 것 같아요.
      
      ```
      {
        "isSuccess": true,
        "code": "COMMON201",
        "message": "생성되었습니다.",
        "data": {
          "id": 1
        }
      }
      ```

2.  키워드 검색 API 설계 변경을 제안드립니다.  제안을 드리는 API 목록은 다음과 같아요.

      ```
          @GetMapping("/search/tracks/{keyword}")
          @Operation(summary = "키워드로 트랙 검색하기")
          public ApiResponse<?> searchTracks(
                  @PathVariable("keyword") String keyword,
                   //...
                  ) {
         //...
          }
      
          @GetMapping("/search/albums/{keyword}")
          @Operation(summary = "키워드로 앨범 검색하기")
          public ApiResponse<?> searchAlbums(
                  @PathVariable("keyword") String keyword,
                  //...
          ) {
          //...
          }
      
          @GetMapping("/search/artists/{keyword}")
          @Operation(summary = "키워드로 아티스트 검색하기")
          public ApiResponse<?> searchArtists(
                  @PathVariable("keyword") String keyword,
                   //...
          ) {
          //...
          }
      ```
      `RESTful API`에서 `@PathVariable`은 주로 리소스를 **고유하게** 식별하는 데 사용됩니다. 예를 들어, 특정 앨범의 ID나 사용자의 ID 등을 경로 변수로 사용하는 것이 일반적이에요. URL 경로 자체가 리소스를 가리키도록 말이죠.
      
      반면에, 키워드 값은 리소스의 고유한 값이라기보다는 **변할 수 있는 값**입니다. 따라서 리소스를 필터링 하는 행위에 해당하므로, **쿼리 파라미터를 이용한 설계**를 추천드립니다.

    
3. 컨트롤러 괄호 위치 통일을 제안 드립니다.    

      댓글 관련 컨트롤러의 소괄호, 중괄호의 위치는 다음과 같습니다.    
      ![image](https://github.com/user-attachments/assets/3baf470b-af43-47c7-a41c-f391db12c23f)
      
      그 외 컨트롤러의 소괄호, 중괄호의 위치는 다음과 같습니다.    
      ![image](https://github.com/user-attachments/assets/ed1c2c7f-5697-4fa4-9a46-0547d22ceb97)
      
      두 방식 중 하나를 선택하면 좋을 것 같습니다. 저는 후자의 방식이 더 깔끔하다고 생각해서. 후자를 선호하는 편이긴 해요!

4. `BaseEntity`는 단독으로 사용되는 용도가 아닌 엔티티가 상속을 받아서 사용하는 용도이므로 `abstract class`로 만들면 어떨까요?

**Comment by mingmingmon** [comment]
너무 좋습니다! 위 사항들 #35 작업에 추가하도록 하겠습니다

**Comment by mingmingmon** [comment]
- [x] `MusicController`의 음악 업로드 API, `CommentController`에 위치한 일부 API의 응답으로 `id` 값 반환 시 `DTO`에 담아 반환
    
- [x] 키워드 검색 API 설계 시 쿼리 파라미터 사용

      ```
          @GetMapping("/search/tracks/{keyword}")
          @Operation(summary = "키워드로 트랙 검색하기")
          public ApiResponse<?> searchTracks(
                  @PathVariable("keyword") String keyword,
                   //...
                  ) {
         //...
          }
      
          @GetMapping("/search/albums/{keyword}")
          @Operation(summary = "키워드로 앨범 검색하기")
          public ApiResponse<?> searchAlbums(
                  @PathVariable("keyword") String keyword,
                  //...
          ) {
          //...
          }
      
          @GetMapping("/search/artists/{keyword}")
          @Operation(summary = "키워드로 아티스트 검색하기")
          public ApiResponse<?> searchArtists(
                  @PathVariable("keyword") String keyword,
                   //...
          ) {
          //...
          }
      ```



    
- [x] 컨트롤러 괄호 위치 통일
![image](https://github.com/user-attachments/assets/3f778f13-e4fd-4b11-a075-a780f4a0e92a)


   
- [x] `BaseEntity`를 `abstract class`로 수정
